### PR TITLE
Fix `--with-zlib` invocation

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by ararslan** [comment]
cc @felipenoris

**Comment by ararslan** [comment]
Is any of this worth investigating as potentially problematic?
```
Info: Mounting /home/travis/build/bicycle1885/XML2Builder/downloads/rootfs-x86_64-apple-darwin14.squashfs to /home/travis/.julia/v0.6/BinaryBuilder/deps/shards/x86_64-apple-darwin14
......................error: /opt/x86_64-apple-darwin14/bin/install_name_tool: for: bin/xmlcatalog (for architecture x86_64) option "-add_rpath @loader_path/../lib" would duplicate path, file already has LC_RPATH for: @loader_path/../lib
Warning: Linked library /usr/lib/libiconv.2.dylib could not be resolved and could not be auto-mapped
error: /opt/x86_64-apple-darwin14/bin/install_name_tool: for: bin/xmllint (for architecture x86_64) option "-add_rpath @loader_path/../lib" would duplicate path, file already has LC_RPATH for: @loader_path/../lib
Warning: Linked library /usr/lib/libiconv.2.dylib could not be resolved and could not be auto-mapped
Warning: Linked library /usr/lib/libiconv.2.dylib could not be resolved and could not be auto-mapped
..Info: Unmounting /home/travis/.julia/v0.6/BinaryBuilder/deps/shards/x86_64-apple-darwin14`
Info: Mounting /home/travis/build/bicycle1885/XML2Builder/downloads/rootfs-x86_64-unknown-freebsd11.1.squashfs to /home/travis/.julia/v0.6/BinaryBuilder/deps/shards/x86_64-unknown-freebsd11.1
.....................Warning: Linked library liblzma.so.5 could not be resolved and could not be auto-mapped
Warning: Linked library liblzma.so.5 could not be resolved and could not be auto-mapped
Warning: Linked library liblzma.so.5 could not be resolved and could not be auto-mapped
..Info: Unmounting /home/travis/.julia/v0.6/BinaryBuilder/deps/shards/x86_64-unknown-freebsd11.1`
```

**Comment by Keno** [comment]
> error: /opt/x86_64-apple-darwin14/bin/install_name_tool: for: bin/xmlcatalog (for architecture > x86_64) option "-add_rpath @loader_path/../lib" would duplicate path, file already has LC_RPATH for: @loader_path/../lib

This is probably worth filing a BinaryBuilder issue about.

I wouldn't worry about the rest if the resulting binary works.

**Comment by ararslan** [comment]
Bump @bicycle1885. This should be good to go.

**Comment by felipenoris** [comment]
did you test it?

**Comment by bicycle1885** [comment]
i'm now trying build binaries on my local Ubuntu VM.

**Comment by bicycle1885** [comment]
It seems to be working on my machines. Let's re-build binaries and test them in <https://github.com/bicycle1885/EzXML.jl/pull/68>.

**Pull request merged**
